name: Auto XT Bot
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # هر ساعت یک‌بار اجرا می‌شود

jobs:
  run-bot:
    runs-on: ubuntu-latest # سیستم‌عامل انتخابی

    steps:
      # Checkout repository
      - name: Checkout repo
        uses: actions/checkout@v2

      # Set up Python with a valid version
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # تغییر به نسخه معتبر مثل 3.9

      # Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run the bot script
      - name: Run bot
        run: python auto_xt_bot.py
        env:
          API_KEY: ${{ secrets.XT_API_KEY }} # اضافه کردن API_KEY از تنظیمات secrets
          API_SECRET: ${{ secrets.XT_API_SECRET }} # اضافه کردن API_SECRET از تنظیمات secrets
